### ISSUE TITLE
Bug ?

### ISSUE THREAD

**Issue by I-Own-You** [luckasRanarison/nvim-devdocs#22]
After update:
<li> when i try to download some documentation, the neovim is literally freezed, and when the docs are downloaded, it then goes normal way(such problems were not encountered before)</li>
<br>

if i put some documentation for example python or lua, like this `ensure_installed = { "lua", "python" }`, then docs are not dowloaded and _**i get an error**_ that documentation doesnt exist for this filetypes, but the problem i guess is that the docs comes with versions, while i put only the filetype name.

**Comment by luckasRanarison** [comment]
With the update docs are now built at download time and writing files is done synchronously and blocks the input, you may want to download larger docs in headless mode now. Maybe I can create a separate program for that in the future instead of depending on neovim for package management. 

You need to specify the version for the lua and python docs
