### ISSUE TITLE
Previewer not showing up in Open commands

### ISSUE THREAD

**Issue by albertocerrone** [luckasRanarison/nvim-devdocs#5]
Hello hello!

I have a little issue with the previewer that is not showing up from telescope when using the Open commands: 
![Screenshot 2023-08-11 at 11 50 58](https://github.com/luckasRanarison/nvim-devdocs/assets/72306953/914804ce-daed-4c87-b98a-2c1a46d489be)

I have a very basic config, so how do I add the previewer?

```lua
  {
    "luckasRanarison/nvim-devdocs",
    cmd = { "DevdocsFetch", "DevdocsInstall", "DevdocsUpdate", "DevdocsUpdateAll", "DevdocsUninstall", "DevdocsOpen",
      "DevdocsOpenFloat", },
    opts = {
      ensure_installed = {
        "python-3.11",
        "django-4.2",
        "bootstrap-5"
      },
    },
    dependencies = {
      "nvim-lua/plenary.nvim",
      "nvim-telescope/telescope.nvim",
      "nvim-treesitter/nvim-treesitter",
    },
  },
```

Thank you so much 🔥
P.S. well done with your first nvim plugin! Very very good job

**Comment by luckasRanarison** [comment]
Thanks for giving my plugin a try! Sorry I should mention it in the README, the previewer only work when opening a specific documentation like `:DevdocsOpen javascript`. I haven't implement it yet because I'm still learning about async events, but that should be possible. All read/write operations are all synchronous for the moment and processing the documentation take some moment to complete and will block the input. I'll add that soon :)

**Comment by albertocerrone** [comment]
I can add it to the docs if is fine for you 🤗

**Comment by luckasRanarison** [comment]
Contributions are welcome :) , I'm also bad at explaining how things work...

**Comment by albertocerrone** [comment]
Don't worry, you explained everything correctly 🤗
